import type { Category } from './types'

export const categories: Category[] = [
  'Eating Out',
  'Housing',
  'Groceries',
  'Transportation',
  'Utilities',
  'Medical',
  'Education',
  'Shopping',
  'Entertainment',
  'Insurance',
  'Subscription',
  'Travel',
]

export const starterRules: Record<Category, string[]> = {
  'Eating Out': [
    'cafe',
    'restaurant',
    'lunch',
    'dinner',
    'brunch',
    'coffee',
    'dessert',
    'bakery',
    'bar',
    'pub',
    'bistro',
    'diner',
    'takeout',
    'takeaway',
    'delivery',
    'pizza',
    'sushi',
    'ramen',
    'burger',
    'steakhouse',
    'bbq',
  ],
  Housing: [
    'rent',
    'mortgage',
    'landlord',
    'property',
    'lease',
    'rental',
    'apartment',
    'condo',
    'hoa',
    'maintenance',
    'repair',
    'renovation',
  ],
  Groceries: [
    'market',
    'supermarket',
    'grocery',
    'groceries',
    'parknshop',
    'wellcome',
    'produce',
    'butcher',
    'deli',
    'fresh',
    'pantry',
    'convenience',
    'toiletries',
    'toilet paper',
    'paper towel',
    'soap',
    'shampoo',
    'conditioner',
    'toothpaste',
    'detergent',
    'laundry',
    'cleaning',
    'household',
    'daily necessities',
  ],
  Transportation: [
    'mtr',
    'taxi',
    'uber',
    'bus',
    'train',
    'octopus',
    'metro',
    'subway',
    'tram',
    'ferry',
    'rideshare',
    'fuel',
    'gasoline',
    'petrol',
    'parking',
    'toll',
    'carwash',
    'vehicle',
  ],
  Utilities: [
    'electric',
    'electricity',
    'water',
    'gas',
    'utility',
    'broadband',
    'internet',
    'wifi',
    'phone',
    'mobile',
    'cellphone',
    'sim',
    'sim card',
    'simcard',
    'sewage',
    'trash',
    'garbage',
    'waste',
    'heating',
    'cooling',
  ],
  Medical: [
    'doctor',
    'clinic',
    'hospital',
    'pharmacy',
    'dental',
    'dentist',
    'vision',
    'optometrist',
    'therapy',
    'medication',
    'prescription',
  ],
  Education: [
    'course',
    'tuition',
    'school',
    'class',
    'lesson',
    'university',
    'college',
    'textbook',
    'training',
    'workshop',
    'seminar',
  ],
  Shopping: [
    'mall',
    'shop',
    'store',
    'amazon',
    'taobao',
    'retail',
    'clothing',
    'apparel',
    'shoes',
    'electronics',
    'gadget',
    'homeware',
    'stationery',
    'notebook',
    'pens',
    'gift',
    'baby',
    'pet',
  ],
  Entertainment: [
    'cinema',
    'movie',
    'concert',
    'game',
    'netflix',
    'theatre',
    'theater',
    'museum',
    'exhibition',
    'amusement',
    'tickets',
    'sports',
    'snowboard',
    'ski',
  ],
  Insurance: [
    'insurance',
    'premium',
    'policy',
    'coverage',
    'auto insurance',
    'health insurance',
    'life insurance',
  ],
  Subscription: [
    'subscription',
    'spotify',
    'apple',
    'icloud',
    'membership',
    'prime',
    'disney',
    'hulu',
    'youtube',
  ],
  Travel: [
    'hotel',
    'flight',
    'airline',
    'trip',
    'booking',
    'airbnb',
    'hostel',
    'resort',
    'visa',
    'passport',
  ],
}

export const commonCurrencies = [
  'HKD',
  'USD',
  'CNY',
  'JPY',
  'EUR',
  'GBP',
  'AUD',
  'CAD',
  'SGD',
  'TWD',
  'KRW',
  'THB',
]
